name: Continuos Integration Workflow

on:
  pull_request:
    branches: [main]

jobs:
  lint_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Dependencies
      - run: npm ci

      - name: Check for Lint
      - run: npm run pre-commit

      - name: Build Project
      - run: npm run build
